# Generated by Django 5.1 on 2025-01-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nilaiMahasiswa',
            fields=[
                ('mahasiswa_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nama_mahasiswa', models.CharField(max_length=512)),
                ('nim', models.IntegerField()),
                ('angkatan', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('IPD', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('IKA', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('RAD', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('SRM', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('KDK', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('MPK', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ANT', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('MAT', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('IKM', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('THTKL', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('KJW', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('OT2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('BED', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('OBG', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('FOR', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('MOI', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ELK', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hasil_ukmppd', models.IntegerField(blank=True, choices=[(0, 'Retake'), (1, 'Lulus')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
