# Generated by Django 4.2.16 on 2025-01-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataNilai', '0002_rename_nim_nilaimahasiswa_nim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='caseRetake',
            fields=[
                ('case_ID', models.AutoField(primary_key=True, serialize=False)),
                ('case', models.CharField(max_length=512)),
                ('semester', models.CharField(max_length=20)),
                ('IPD', models.FloatField(blank=True, null=True)),
                ('IKA', models.FloatField(blank=True, null=True)),
                ('RAD', models.FloatField(blank=True, null=True)),
                ('SRM', models.FloatField(blank=True, null=True)),
                ('KDK', models.FloatField(blank=True, null=True)),
                ('MPK', models.FloatField(blank=True, null=True)),
                ('ANT', models.FloatField(blank=True, null=True)),
                ('MAT', models.FloatField(blank=True, null=True)),
                ('IKM', models.FloatField(blank=True, null=True)),
                ('THTKL', models.FloatField(blank=True, null=True)),
                ('KJW', models.FloatField(blank=True, null=True)),
                ('OT2', models.FloatField(blank=True, null=True)),
                ('BED', models.FloatField(blank=True, null=True)),
                ('OBG', models.FloatField(blank=True, null=True)),
                ('FOR', models.FloatField(blank=True, null=True)),
                ('MOI', models.FloatField(blank=True, null=True)),
                ('ELK', models.FloatField(blank=True, null=True)),
                ('solution', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='nilaimahasiswa',
            name='solution',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
