# Generated by Django 5.1 on 2025-01-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetrainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_semester', models.CharField(max_length=20)),
                ('f1_score', models.FloatField()),
                ('retrained_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
