# Generated by Django 4.2.16 on 2024-12-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hasilUKMPPD',
            fields=[
                ('mahasiswa_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_mahasiswa', models.CharField(max_length=200)),
                ('angkatan', models.CharField(max_length=20)),
                ('periode_ukmppd', models.CharField(max_length=50)),
                ('hasil_ukmppd', models.CharField(max_length=20)),
            ],
        ),
    ]
