# Generated by Django 4.2.16 on 2024-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUKMPPD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilukmppd',
            name='NIM',
            field=models.IntegerField(default=0),
        ),
    ]
