# Generated by Django 5.1 on 2025-01-06 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUKMPPD', '0002_hasilukmppd_nim'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilukmppd',
            name='ANT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='BED',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='ELK',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='FOR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='IKA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='IKM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='IPD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='KDK',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='KJW',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='MAT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='MOI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='MPK',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='OBG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='OT2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='RAD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='SRM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='THTKL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hasilukmppd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hasilukmppd',
            name='NIM',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hasilukmppd',
            name='hasil_ukmppd',
            field=models.IntegerField(choices=[(0, 'Retake'), (1, 'Lulus')]),
        ),
        migrations.AlterField(
            model_name='hasilukmppd',
            name='mahasiswa_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hasilukmppd',
            name='nama_mahasiswa',
            field=models.CharField(max_length=512),
        ),
    ]
